"""LIVE ARBITRAGE EXECUTOR — Binance <-> Bybit spot, ANY common symbol,
EITHER direction (Phase 3A built this for LUNCUSDT/Binance-buy/Bybit-sell
only; Phase 3, user directive, 2026-08-23, generalizes it: "ne hardcode
pas ... une liste arbitraire" — the symbol/direction are now call-time
parameters, chosen by app.execution.live_ranker from the dynamically
discovered common universe, never fixed in this module).

DANGER: this module can place two real market orders. It is the ONLY
caller of app.execution.binance_live_trade_client and
app.execution.bybit_live_trade_client in the entire codebase
(tests/test_phase3a_isolation.py proves this) and is NEVER imported by
main.py's detection loop or any other automatically-running code — every
invocation of execute_one_arbitrage() is a deliberate, individually
authorized act by an operator, never a loop.

There is no real atomicity between two different exchanges. This module
treats that as the central design constraint, not an edge case:

- Every order submission uses a caller-supplied, unique client order id
  — never generated by retrying with the same id, never reused.
- An ACK (the response from placing an order) is NEVER treated as a fill
  confirmation — every submission is followed by polling
  get_order_status until a genuinely terminal state or a strict timeout.
- A timeout without a terminal status is treated as UNKNOWN, not as
  "probably didn't fill" or "probably did" — the kill switch engages
  immediately and the attempt ends requiring manual reconciliation. This
  module never guesses.
- If the buy leg fills but the sell leg does not, the resulting position
  is NEUTRALIZED by an immediate market sell on the SAME exchange the buy
  happened on — never left as naked directional exposure, and never
  "fixed" by blindly retrying the other leg (which could double the
  position if the first attempt actually succeeded after all under an
  ambiguous response).
- max_concurrent_live_arbitrages (checked via
  app.execution.live_guard.live_guard) prevents two attempts from
  overlapping in the first place — the simplest possible defense against
  compounding leg risk.

Every attempt, whatever its outcome, is meant to be recorded to the
Profit Reality Ledger (app.database.repository.save_live_arbitrage_execution)
by the caller — this module returns a complete LiveArbitrageResult
either way, including for NO_TRADE and UNKNOWN outcomes, so the ledger
never has a "silent gap" for an attempt that was actually made.
"""

import asyncio
import logging
import time
import uuid
from dataclasses import dataclass, field
from enum import StrEnum

from app.execution.binance_account_client import BinanceAccountClient
from app.execution.binance_filters import parse_symbol_rules as parse_binance_symbol_rules
from app.execution.binance_filters import round_down_to_step
from app.execution.binance_live_trade_client import BinanceLiveTradeClient, aggregate_binance_trades
from app.execution.bybit_client import BybitClient, parse_wallet_balance
from app.execution.bybit_live_trade_client import BybitLiveTradeClient
from app.execution.dual_leg_quote import DualLegQuote, LegSnapshot, compute_common_dual_leg_qty, compute_dual_leg_quote
from app.execution.live_guard import LiveExecutionRefused, live_guard
from app.execution.okx_account_client import OkxAccountClient
from app.execution.okx_live_trade_client import OkxLiveTradeClient
from app.execution.reality_quote import DEFAULT_TAKER_FEE_RATE, _vwap_for_target_qty
from app.scanner.okx_public_client import OkxPublicClient

logger = logging.getLogger(__name__)

LEG_CONFIRMATION_TIMEOUT_SECONDS = 15.0
LEG_POLL_INTERVAL_SECONDS = 0.5
EXCHANGES = ("binance", "bybit", "okx")
QUOTE_ASSET = "USDT"  # every symbol in this codebase is USDT-quoted (app.execution.inventory_manager's own convention)


def direction_for(buy_exchange: str, sell_exchange: str) -> str:
    return f"{buy_exchange.upper()}_BUY_{sell_exchange.upper()}_SELL"


def _bare_symbol_to_okx(symbol: str) -> str:
    """This module's own symbols are bare, Binance-style ("LUNCUSDT", no
    separator) -- app.execution.okx_account_client/okx_live_trade_client/
    app.scanner.okx_public_client all expect the "/"-separated form
    ("LUNC/USDT") and convert to OKX's own "-" form internally. Every
    OKX call site below goes through this first."""
    return f"{symbol.removesuffix(QUOTE_ASSET)}/{QUOTE_ASSET}"


def resolve_fee(fees_by_asset: dict[str, float], base_asset: str, avg_fill_price: float | None, log_prefix: str) -> tuple[str | None, float, float | None]:
    """Pure function. Duplicated from app.execution.inventory_constitution_executor
    on purpose (see module docstring — these two files deliberately do not
    share code). Returns (fee_asset, fee_amount, fee_usd_equivalent) —
    NEVER assumes a currency (2026-08-24 fix, after the first real Bybit
    fill mislabeled a 2.9179 RVN fee as $2.9179)."""
    nonzero = {asset: amount for asset, amount in fees_by_asset.items() if amount}
    if not nonzero:
        return None, 0.0, 0.0
    if len(nonzero) > 1:
        logger.warning("%s: order fee charged in multiple assets, cannot compute a single USD equivalent: %s", log_prefix, nonzero)
        return None, 0.0, None
    (fee_asset, fee_amount), = nonzero.items()
    if fee_asset == QUOTE_ASSET:
        return fee_asset, fee_amount, fee_amount
    if fee_asset == base_asset and avg_fill_price is not None and avg_fill_price > 0:
        return fee_asset, fee_amount, fee_amount * avg_fill_price
    logger.warning("%s: order fee charged in unrecognized asset %s, cannot compute a USD equivalent without a price for it", log_prefix, fee_asset)
    return fee_asset, fee_amount, None


def net_base_qty_after_fee(gross_qty: float, fee_asset: str | None, fee_amount: float, base_asset: str) -> float:
    """Pure function, duplicated from inventory_constitution_executor.py.
    The base-asset quantity actually held after a fill — only reduced by
    the fee when the fee itself was charged in that SAME base asset."""
    if fee_asset == base_asset:
        return max(0.0, gross_qty - fee_amount)
    return gross_qty


class ArbitrageOutcome(StrEnum):
    NO_TRADE_REFUSED = "no_trade_refused"  # live_guard refused before any order was even considered
    NO_TRADE_UNPROFITABLE = "no_trade_unprofitable"  # fresh dual-leg re-check failed the safety-margin gate — no order sent
    NO_FILL = "no_fill"  # buy leg rejected/expired with zero fill — nothing to neutralize
    BOTH_FILLED = "both_filled"
    BUY_ONLY_NEUTRALIZED = "buy_only_neutralized"  # sell leg failed; flattened on the buy exchange
    NEUTRALIZATION_FAILED = "neutralization_failed"  # CRITICAL — manual intervention required, kill switch engaged
    UNKNOWN_BUY_LEG = "unknown_buy_leg"  # timeout/ambiguous response — kill switch engaged
    UNKNOWN_SELL_LEG = "unknown_sell_leg"  # timeout/ambiguous response — kill switch engaged


@dataclass(slots=True)
class LiveArbitrageResult:
    attempt_id: uuid.UUID
    symbol: str
    buy_exchange: str
    sell_exchange: str
    outcome: ArbitrageOutcome
    reason: str | None

    predicted_net_profit_usd: float | None = None
    predicted_fees_usd: float | None = None
    predicted_slippage_pct: float | None = None
    safety_adjusted_predicted_profit_usd: float | None = None

    buy_client_order_id: str | None = None
    buy_exchange_order_id: str | None = None
    buy_status: str | None = None
    buy_filled_qty: float = 0.0  # GROSS, exactly as reported by the exchange
    buy_net_filled_qty: float = 0.0  # ACTUALLY held after the buy fill — see net_base_qty_after_fee
    buy_avg_fill_price: float | None = None
    buy_fee_asset: str | None = None  # never assume a Bybit/Binance fee is in USDT
    buy_fee_amount: float | None = None
    buy_fee_usd_equivalent: float | None = None
    buy_fees_usd: float | None = None  # backward-compat alias — equal to buy_fee_usd_equivalent from this fix onward
    buy_submitted_at: float | None = None
    buy_confirmed_at: float | None = None

    sell_client_order_id: str | None = None
    sell_exchange_order_id: str | None = None
    sell_status: str | None = None
    sell_filled_qty: float = 0.0
    sell_avg_fill_price: float | None = None
    sell_fee_asset: str | None = None
    sell_fee_amount: float | None = None
    sell_fee_usd_equivalent: float | None = None
    sell_fees_usd: float | None = None  # backward-compat alias — equal to sell_fee_usd_equivalent from this fix onward
    sell_submitted_at: float | None = None
    sell_confirmed_at: float | None = None

    neutralization_order_id: str | None = None
    neutralization_filled_qty: float = 0.0

    actual_net_pnl_usd: float | None = None
    prediction_error_usd: float | None = None

    started_at: float = field(default_factory=time.time)
    completed_at: float | None = None


@dataclass(slots=True)
class _NormalizedOrderStatus:
    order_id: str
    is_terminal: bool
    is_filled: bool
    filled_qty: float  # GROSS — as reported by the exchange
    net_base_qty: float  # ACTUALLY held after the fill — see net_base_qty_after_fee
    avg_fill_price: float | None
    fee_asset: str | None
    fee_amount: float
    fee_usd_equivalent: float | None
    raw_status: str


class LiveArbitrageExecutor:
    def __init__(
        self,
        binance_read: BinanceAccountClient | None = None,
        binance_trade: BinanceLiveTradeClient | None = None,
        bybit_read: BybitClient | None = None,
        bybit_trade: BybitLiveTradeClient | None = None,
        okx_read: OkxAccountClient | None = None,
        okx_public: OkxPublicClient | None = None,
        okx_trade: OkxLiveTradeClient | None = None,
    ) -> None:
        self._binance_read = binance_read or BinanceAccountClient()
        self._binance_trade = binance_trade or BinanceLiveTradeClient()
        self._bybit_read = bybit_read or BybitClient()
        self._bybit_trade = bybit_trade or BybitLiveTradeClient()
        self._okx_read = okx_read or OkxAccountClient()
        self._okx_public = okx_public or OkxPublicClient()
        self._okx_trade = okx_trade or OkxLiveTradeClient()

    async def _fresh_dual_leg_quote(
        self, symbol: str, buy_exchange: str, sell_exchange: str, micro_live_cap_usdt: float, master_requested_size_usd: float
    ) -> tuple[DualLegQuote, LegSnapshot, LegSnapshot] | None:
        """Re-runs the EXACT Phase 2F dual-leg reality check with brand
        new live data, for whichever (buy_exchange, sell_exchange) pair
        is being attempted — never trusts a quote computed even seconds
        ago for the actual go/no-go decision."""
        try:
            buy_leg = await self._fetch_leg_snapshot(symbol, buy_exchange, "buy")
            sell_leg = await self._fetch_leg_snapshot(symbol, sell_exchange, "sell")
            if buy_leg is None or sell_leg is None:
                return None
            quote = compute_dual_leg_quote(
                opportunity_id=uuid.uuid4(),
                symbol=symbol,
                buy_leg=buy_leg,
                sell_leg=sell_leg,
                master_requested_size_usd=master_requested_size_usd,
                micro_live_cap_usdt=micro_live_cap_usdt,
            )
            return quote, buy_leg, sell_leg
        except Exception as exc:
            logger.warning("live-arbitrage: fresh dual-leg re-check failed for %s %s->%s: %s", symbol, buy_exchange, sell_exchange, exc)
            return None

    async def _fetch_leg_snapshot(self, symbol: str, exchange: str, side: str) -> LegSnapshot | None:
        now = time.time()
        if exchange == "binance":
            book = await self._binance_read.get_book_ticker(symbol)
            depth = await self._binance_read.get_order_book_depth(symbol, limit=20)
            info = await self._binance_read.get_exchange_info(symbols=[symbol])
            rules = parse_binance_symbol_rules(info, symbol)
            fee = await self._binance_read.get_trade_fee(symbol)
            depth_levels = [(float(p), float(q)) for p, q in depth.get("asks" if side == "buy" else "bids", [])]
            return LegSnapshot(
                exchange="binance",
                side=side,
                best_bid=float(book["bidPrice"]),
                best_ask=float(book["askPrice"]),
                depth_levels=depth_levels,
                min_qty=rules.min_qty,
                step_size=rules.step_size,
                tick_size=rules.tick_size,
                min_notional=rules.min_notional,
                tradable=(rules.status == "TRADING" and rules.is_spot_trading_allowed),
                maker_fee_rate=fee.maker_fee_rate if fee is not None else None,
                taker_fee_rate=fee.taker_fee_rate if fee is not None else DEFAULT_TAKER_FEE_RATE,
                fee_source="real_account_fee" if fee is not None else "estimated_default",
                fetch_started_at=now,
                fetch_completed_at=time.time(),
            )
        elif exchange == "bybit":
            book = await self._bybit_read.get_book_ticker(symbol)
            if book is None:
                return None
            depth = await self._bybit_read.get_order_book_depth(symbol, limit=50)
            rules = await self._bybit_read.get_symbol_rules(symbol)
            if rules is None:
                return None
            fee = await self._bybit_read.get_fee_rate(symbol)
            side_key = "a" if side == "buy" else "b"
            depth_levels = [(float(p), float(q)) for p, q in depth.get("result", {}).get(side_key, [])]
            return LegSnapshot(
                exchange="bybit",
                side=side,
                best_bid=book.bid_price,
                best_ask=book.ask_price,
                depth_levels=depth_levels,
                min_qty=rules.min_order_qty,
                step_size=rules.qty_step,
                tick_size=rules.tick_size,
                min_notional=rules.min_order_amt,
                tradable=rules.is_tradable,
                maker_fee_rate=fee.maker_fee_rate if fee is not None else None,
                taker_fee_rate=fee.taker_fee_rate if fee is not None else DEFAULT_TAKER_FEE_RATE,
                fee_source="real_account_fee" if fee is not None else "estimated_default",
                fetch_started_at=now,
                fetch_completed_at=time.time(),
            )
        elif exchange == "okx":
            okx_symbol = _bare_symbol_to_okx(symbol)
            book = await self._okx_public.get_book_ticker(okx_symbol)
            if book is None:
                return None
            depth = await self._okx_public.get_order_book_depth(okx_symbol, limit=20)
            rules = await self._okx_public.get_symbol_rules(okx_symbol)
            if rules is None:
                return None
            try:
                fee = await self._okx_read.get_trade_fee(okx_symbol)
            except Exception:
                fee = None  # OkxCredentialsMissing or a transient failure -- fall back to the estimated default, never block the leg fetch
            book_data = depth.get("data", [{}])
            levels = book_data[0] if book_data else {}
            side_key = "asks" if side == "buy" else "bids"
            depth_levels = [(float(p), float(q)) for p, q, *_ in levels.get(side_key, [])]
            return LegSnapshot(
                exchange="okx",
                side=side,
                best_bid=book.bid_price,
                best_ask=book.ask_price,
                depth_levels=depth_levels,
                min_qty=rules.min_qty,
                step_size=rules.lot_size,
                tick_size=rules.tick_size,
                min_notional=None,  # OKX spot publishes no separate notional floor; minSz (base asset) is the binding constraint
                tradable=rules.is_tradable,
                maker_fee_rate=fee.maker_fee_rate if fee is not None else None,
                taker_fee_rate=fee.taker_fee_rate if fee is not None else DEFAULT_TAKER_FEE_RATE,
                fee_source="real_account_fee" if fee is not None else "estimated_default",
                fetch_started_at=now,
                fetch_completed_at=time.time(),
            )
        else:
            raise ValueError(f"unknown exchange {exchange!r}")

    async def _await_terminal(self, poll_fn, timeout_seconds: float) -> tuple[bool, object | None]:
        """Polls poll_fn() until it returns a terminal result or the
        timeout elapses. Returns (reached_terminal, last_result) — NEVER
        raises; a poll error just means one more retry until the
        timeout, since polling status is read-only and safe to repeat
        (unlike submitting an order)."""
        deadline = time.time() + timeout_seconds
        last_result = None
        while time.time() < deadline:
            try:
                last_result = await poll_fn()
            except Exception as exc:
                logger.warning("live-arbitrage: status poll failed, retrying: %s", exc)
                last_result = None
            if last_result is not None and getattr(last_result, "is_terminal", False):
                return True, last_result
            await asyncio.sleep(LEG_POLL_INTERVAL_SECONDS)
        return False, last_result

    async def _get_available_base_balance(self, exchange: str, symbol: str) -> float:
        """Fresh real balance read — never a cached/estimated figure.
        Used both for pre-trade common_qty sizing and by _neutralize,
        which must always cap by the real balance immediately before
        submitting (item 3, user directive, 2026-08-24, post-incident)."""
        base_asset = symbol.removesuffix(QUOTE_ASSET)
        if exchange == "binance":
            snapshot = await self._binance_read.get_account_snapshot()
            return snapshot.balance_of(base_asset) if snapshot is not None else 0.0
        if exchange == "bybit":
            wallet = await self._bybit_read.get_wallet_balance()
            return parse_wallet_balance(wallet, base_asset)
        if exchange == "okx":
            snapshot = await self._okx_read.get_account_snapshot()
            return snapshot.balance_of(base_asset) if snapshot is not None else 0.0
        raise ValueError(f"unknown exchange {exchange!r}")

    async def _place_market_buy(self, exchange: str, symbol: str, qty: float, client_order_id: str) -> None:
        """Item 1 fix (2026-08-24, post-incident): the arbitrage buy leg
        is QUANTITY-capped, never notional-capped — common_qty exists
        specifically so the buy leg can never acquire more base asset
        than the sell leg can actually absorb, which only holds if the
        buy itself is bounded by quantity. (Contrast with
        app.execution.inventory_constitution_executor's OWN
        _place_market_buy, deliberately unchanged and still
        notional-based — inventory constitution has no second leg to
        stay in sync with.) OKX's tgtCcy=base_ccy (set unconditionally
        inside OkxLiveTradeClient.place_market_order) gives the same
        quantity-in-base-asset guarantee as Binance's `quantity=`/
        Bybit's market_unit="baseCoin" above."""
        if exchange == "binance":
            await self._binance_trade.place_market_order(symbol, "BUY", client_order_id=client_order_id, quantity=qty)
        elif exchange == "bybit":
            await self._bybit_trade.place_market_order(symbol, "Buy", qty=qty, order_link_id=client_order_id, market_unit="baseCoin")
        elif exchange == "okx":
            await self._okx_trade.place_market_order(_bare_symbol_to_okx(symbol), "buy", qty, client_order_id=client_order_id)
        else:
            raise ValueError(f"unknown exchange {exchange!r}")

    async def _place_market_sell(self, exchange: str, symbol: str, qty: float, client_order_id: str) -> None:
        if exchange == "binance":
            await self._binance_trade.place_market_order(symbol, "SELL", client_order_id=client_order_id, quantity=qty)
        elif exchange == "bybit":
            await self._bybit_trade.place_market_order(symbol, "Sell", qty=qty, order_link_id=client_order_id)
        elif exchange == "okx":
            await self._okx_trade.place_market_order(_bare_symbol_to_okx(symbol), "sell", qty, client_order_id=client_order_id)
        else:
            raise ValueError(f"unknown exchange {exchange!r}")

    async def _get_status(self, exchange: str, symbol: str, client_order_id: str) -> _NormalizedOrderStatus | None:
        base_asset = symbol.removesuffix(QUOTE_ASSET)
        if exchange == "binance":
            result = await self._binance_trade.get_order_status(symbol, orig_client_order_id=client_order_id)
            if not result.is_terminal or result.executed_qty <= 0:
                # Not yet resolved, or resolved with zero fill — no real
                # trades to fetch; get_order_status's own qty/status are
                # already reliable for this case (there is no fee to mis-report).
                return _NormalizedOrderStatus(
                    order_id=str(result.order_id), is_terminal=result.is_terminal, is_filled=result.is_filled,
                    filled_qty=result.executed_qty, net_base_qty=result.executed_qty,
                    avg_fill_price=result.average_fill_price(),
                    fee_asset=None, fee_amount=0.0, fee_usd_equivalent=0.0,
                    raw_status=result.status,
                )
            # Item 2 fix (2026-08-24, post-incident): get_order_status's
            # own endpoint never returns fills, so the first real
            # arbitrage attempt's buy leg reported fee_asset=None despite
            # a real ~3 RVN fee having been charged — fetch the REAL
            # trades for this order via get_order_trades, the only call
            # that actually exposes commission/commissionAsset/price/qty.
            trades = await self._binance_trade.get_order_trades(symbol, result.order_id)
            aggregated = aggregate_binance_trades(trades)
            gross_qty = aggregated.gross_base_qty if trades else result.executed_qty
            avg_price = aggregated.actual_effective_price if trades else result.average_fill_price()
            fee_asset, fee_amount, fee_usd_equivalent = resolve_fee(aggregated.fees_by_asset, base_asset, avg_price, "live-arbitrage")
            return _NormalizedOrderStatus(
                order_id=str(result.order_id),
                is_terminal=result.is_terminal,
                is_filled=result.is_filled,
                filled_qty=gross_qty,
                net_base_qty=net_base_qty_after_fee(gross_qty, fee_asset, fee_amount, base_asset),
                avg_fill_price=avg_price,
                fee_asset=fee_asset, fee_amount=fee_amount, fee_usd_equivalent=fee_usd_equivalent,
                raw_status=result.status,
            )
        elif exchange == "bybit":
            status = await self._bybit_trade.get_order_status(symbol, order_link_id=client_order_id)
            if status is None:
                return None
            gross_qty = status.cum_exec_qty
            # Never assume Bybit charged the fee in the quote asset (USDT)
            # — the first real fill (2026-08-24) charged it in RVN, the
            # base asset, mislabeling a $0.01 fee as $2.9179.
            fee_asset, fee_amount, fee_usd_equivalent = resolve_fee(status.total_fees_by_asset(), base_asset, status.avg_price, "live-arbitrage")
            return _NormalizedOrderStatus(
                order_id=status.order_id,
                is_terminal=status.is_terminal,
                is_filled=status.is_filled,
                filled_qty=gross_qty,
                net_base_qty=net_base_qty_after_fee(gross_qty, fee_asset, fee_amount, base_asset),
                avg_fill_price=status.avg_price,
                fee_asset=fee_asset, fee_amount=fee_amount, fee_usd_equivalent=fee_usd_equivalent,
                raw_status=status.order_status,
            )
        elif exchange == "okx":
            status = await self._okx_trade.get_order_status(_bare_symbol_to_okx(symbol), client_order_id=client_order_id)
            if status is None:
                return None
            gross_qty = status.filled_qty
            # Item 4 (user directive, 2026-08-25, "IMPORTANT -- ne jamais
            # supposer que les frais sont en USDT"): OKX's own fee_asset
            # can be the base asset, the quote asset, or an unrelated
            # promotional discount token (e.g. OKB) -- resolve_fee already
            # returns fee_usd_equivalent=None for anything it cannot
            # price, which the caller (execute_one_arbitrage) must treat
            # as a reason to stop, never a reason to assume $0.
            fees_by_asset = {status.fee_asset: status.fee_amount} if status.fee_asset and status.fee_amount else {}
            fee_asset, fee_amount, fee_usd_equivalent = resolve_fee(fees_by_asset, base_asset, status.avg_fill_price, "live-arbitrage")
            return _NormalizedOrderStatus(
                order_id=status.order_id,
                is_terminal=status.is_terminal,
                is_filled=status.is_filled,
                filled_qty=gross_qty,
                net_base_qty=net_base_qty_after_fee(gross_qty, fee_asset, fee_amount, base_asset),
                avg_fill_price=status.avg_fill_price,
                fee_asset=fee_asset, fee_amount=fee_amount, fee_usd_equivalent=fee_usd_equivalent,
                raw_status=status.state,
            )
        else:
            raise ValueError(f"unknown exchange {exchange!r}")

    async def _get_step_size(self, exchange: str, symbol: str) -> tuple[float, float] | None:
        """Returns (step_size, min_qty) for the given exchange/symbol, or
        None if unavailable — used to round a neutralization/hedge
        quantity to what that exchange will actually accept."""
        if exchange == "binance":
            info = await self._binance_read.get_exchange_info(symbols=[symbol])
            rules = parse_binance_symbol_rules(info, symbol)
            return rules.step_size, rules.min_qty
        if exchange == "bybit":
            rules = await self._bybit_read.get_symbol_rules(symbol)
            if rules is None:
                return None
            return rules.qty_step, rules.min_order_qty
        if exchange == "okx":
            rules = await self._okx_public.get_symbol_rules(_bare_symbol_to_okx(symbol))
            if rules is None:
                return None
            return rules.lot_size, rules.min_qty
        raise ValueError(f"unknown exchange {exchange!r}")

    async def _neutralize(self, exchange: str, symbol: str, qty: float, attempt_id: uuid.UUID) -> _NormalizedOrderStatus | None:
        """Flattens an unwanted position acquired on `exchange` with an
        immediate market SELL on that SAME exchange — never attempts to
        "fix" a one-leg-filled state by retrying the other exchange's
        leg, which could double the position if the original attempt
        actually succeeded after all under an ambiguous response.

        Item 3 fix (2026-08-24, post-incident): `qty` is an UPPER BOUND
        only, never trusted blindly — the first real neutralization
        attempt tried to sell 3003.5 RVN (the buy leg's own estimated
        fill) when only 3000.4965 was actually held, and was itself
        rejected by Binance. This always re-reads the REAL free balance
        immediately before submitting and caps to that, floored to the
        exchange's step size, with one extra step of technical reserve —
        this is the last line of defense (a second failure here means
        NEUTRALIZATION_FAILED, kill switch, manual reconciliation), so
        the cost of a small deliberate margin is worth it."""
        real_available = await self._get_available_base_balance(exchange, symbol)
        step = await self._get_step_size(exchange, symbol)
        step_size = step[0] if step is not None else 0.0
        capped_qty = min(qty, real_available)
        safe_qty = round_down_to_step(capped_qty, step_size) if step_size > 0 else capped_qty
        if step_size > 0 and safe_qty > step_size:
            safe_qty -= step_size
        if safe_qty <= 0:
            logger.critical(
                "live-arbitrage: NEUTRALIZATION SKIPPED on %s for %s — no real balance available (requested up to %s, real free balance %s)",
                exchange, attempt_id, qty, real_available,
            )
            return None
        # Bybit's orderLinkId has a documented 36-character max — see the
        # matching fix note on buy_client_order_id/sell_client_order_id
        # below (2026-08-24, real retCode=170003 rejections).
        neutralize_id = f"neu-{attempt_id.hex[:24]}"
        try:
            await self._place_market_sell(exchange, symbol, safe_qty, neutralize_id)
        except Exception as exc:
            logger.critical("live-arbitrage: NEUTRALIZATION ORDER SUBMISSION FAILED on %s for %s: %s", exchange, attempt_id, exc)
            return None
        reached, result = await self._await_terminal(lambda: self._get_status(exchange, symbol, neutralize_id), LEG_CONFIRMATION_TIMEOUT_SECONDS)
        if not reached:
            logger.critical("live-arbitrage: NEUTRALIZATION ORDER STATUS UNKNOWN on %s for %s", exchange, attempt_id)
            return result
        return result

    async def execute_one_arbitrage(
        self,
        symbol: str,
        buy_exchange: str,
        sell_exchange: str,
        requested_notional_per_leg_usdt: float,
        opportunity_id: uuid.UUID | None = None,
    ) -> LiveArbitrageResult:
        """The entire leg-risk-managed attempt, start to finish, for ANY
        symbol/direction pair the caller (app.execution.live_ranker)
        selects from the dynamically-discovered common universe. Callers
        (never main.py's automatic loop — see this module's own
        docstring) are responsible for persisting the returned result to
        the Profit Reality Ledger."""
        if buy_exchange not in EXCHANGES or sell_exchange not in EXCHANGES or buy_exchange == sell_exchange:
            raise ValueError(f"buy_exchange/sell_exchange must be distinct values from {EXCHANGES}, got {buy_exchange!r}/{sell_exchange!r}")

        attempt_id = uuid.uuid4()
        direction = direction_for(buy_exchange, sell_exchange)
        result = LiveArbitrageResult(
            attempt_id=attempt_id, symbol=symbol, buy_exchange=buy_exchange, sell_exchange=sell_exchange,
            outcome=ArbitrageOutcome.NO_TRADE_REFUSED, reason=None,
        )

        try:
            live_guard.assert_arbitrage_allowed(symbol, direction, requested_notional_per_leg_usdt)
        except LiveExecutionRefused as exc:
            result.reason = str(exc)
            result.completed_at = time.time()
            return result

        live_guard.register_arbitrage_start()
        try:
            fresh = await self._fresh_dual_leg_quote(symbol, buy_exchange, sell_exchange, requested_notional_per_leg_usdt, requested_notional_per_leg_usdt)
            if fresh is None:
                result.outcome = ArbitrageOutcome.NO_TRADE_UNPROFITABLE
                result.reason = "fresh dual-leg re-check unavailable (data fetch failed)"
                result.completed_at = time.time()
                return result
            quote, buy_leg, sell_leg = fresh

            result.predicted_net_profit_usd = quote.net_profit_usd
            result.predicted_fees_usd = quote.buy_fee_usd + quote.sell_fee_usd
            result.predicted_slippage_pct = max(quote.buy_slippage_pct, quote.sell_slippage_pct)

            # Same data-driven safety-margin methodology as Phase 2E/2F —
            # no fixed number invented here; a caller with a
            # recommend_safety_margin_usd() figure from
            # app.reporting.dual_leg_edge should pass it forward via
            # requested_notional_per_leg_usdt sizing upstream. In the
            # absence of a supplied margin this defaults to 0 (bare
            # net_profit_usd > 0), which is intentionally the WEAKER
            # bound — callers building the first-live gate must apply
            # the stricter, measured margin themselves before calling.
            safety_margin_usd = 0.0
            result.safety_adjusted_predicted_profit_usd = quote.net_profit_usd - safety_margin_usd

            if not quote.executable or result.safety_adjusted_predicted_profit_usd <= 0:
                result.outcome = ArbitrageOutcome.NO_TRADE_UNPROFITABLE
                result.reason = quote.reason or "net profit after safety margin is not strictly positive"
                result.completed_at = time.time()
                return result

            # Item 1 (user directive, 2026-08-24, post-incident): common
            # dual-leg sizing. quote.executable_qty is already
            # price/depth/notional-aware, but has ZERO knowledge of real
            # account balances — the first real attempt bought 3003.5
            # RVN (sized purely by USDT notional) against only 2914.9821
            # real Bybit inventory. Never again: the sell exchange's REAL
            # available balance is now part of the pre-trade ceiling
            # BOTH legs are sized against, before either order exists.
            sell_exchange_available_qty = await self._get_available_base_balance(sell_exchange, symbol)
            common_qty = compute_common_dual_leg_qty(quote.executable_qty, sell_exchange_available_qty, buy_leg.step_size, sell_leg.step_size)
            if common_qty <= 0 or common_qty < buy_leg.min_qty or common_qty < sell_leg.min_qty:
                result.outcome = ArbitrageOutcome.NO_TRADE_UNPROFITABLE
                result.reason = (
                    f"no common executable quantity after checking real sell-exchange inventory "
                    f"(quote_executable_qty={quote.executable_qty}, sell_exchange_available={sell_exchange_available_qty}, common_qty={common_qty})"
                )
                result.completed_at = time.time()
                return result

            # Revalidate net-positive at the ACTUAL common_qty (which may
            # be smaller than quote.executable_qty once real inventory is
            # considered) before ever submitting an order — reuses the
            # same leg snapshots, no extra network round trip.
            common_notional_usd = common_qty * buy_leg.best_ask
            sized_quote = compute_dual_leg_quote(
                opportunity_id=uuid.uuid4(), symbol=symbol, buy_leg=buy_leg, sell_leg=sell_leg,
                master_requested_size_usd=common_notional_usd, micro_live_cap_usdt=common_notional_usd,
            )
            if not sized_quote.executable or sized_quote.net_profit_usd <= 0:
                result.outcome = ArbitrageOutcome.NO_TRADE_UNPROFITABLE
                result.reason = sized_quote.reason or f"not net-positive at the real common quantity ({common_qty})"
                result.completed_at = time.time()
                return result
            trade_qty = sized_quote.executable_qty
            result.predicted_net_profit_usd = sized_quote.net_profit_usd  # supersede with the size-accurate prediction
            result.safety_adjusted_predicted_profit_usd = sized_quote.net_profit_usd

            # Bybit's orderLinkId has a documented 36-character max — a
            # full "live-{uuid4}-buy" (45 chars) silently exceeded it and
            # is the prime suspect for the real retCode=170003 "unknown
            # parameter" rejections (2026-08-24). attempt_id.hex (32 hex
            # chars, no hyphens) truncated to 24 keeps every variant
            # (buy/sell/neutralize) well under the limit while remaining
            # effectively collision-proof at max_concurrent_live_arbitrages=1.
            buy_client_order_id = f"buy-{attempt_id.hex[:24]}"
            result.buy_client_order_id = buy_client_order_id
            result.buy_submitted_at = time.time()
            try:
                await self._place_market_buy(buy_exchange, symbol, trade_qty, buy_client_order_id)
            except Exception as exc:
                live_guard.engage_kill_switch(f"buy leg submission raised an ambiguous error: {exc}")
                result.outcome = ArbitrageOutcome.UNKNOWN_BUY_LEG
                result.reason = str(exc)
                result.completed_at = time.time()
                return result

            reached, buy_status = await self._await_terminal(
                lambda: self._get_status(buy_exchange, symbol, buy_client_order_id), LEG_CONFIRMATION_TIMEOUT_SECONDS
            )
            if not reached or buy_status is None:
                live_guard.engage_kill_switch(f"buy leg status unknown after timeout for attempt {attempt_id}")
                result.outcome = ArbitrageOutcome.UNKNOWN_BUY_LEG
                result.reason = "buy leg did not reach a terminal status within the confirmation timeout"
                result.completed_at = time.time()
                return result

            result.buy_exchange_order_id = buy_status.order_id
            result.buy_status = buy_status.raw_status
            result.buy_filled_qty = buy_status.filled_qty
            result.buy_net_filled_qty = buy_status.net_base_qty
            result.buy_avg_fill_price = buy_status.avg_fill_price
            result.buy_fee_asset = buy_status.fee_asset
            result.buy_fee_amount = buy_status.fee_amount
            result.buy_fee_usd_equivalent = buy_status.fee_usd_equivalent
            result.buy_fees_usd = buy_status.fee_usd_equivalent  # backward-compat alias, now correctly currency-aware
            result.buy_confirmed_at = time.time()

            if buy_status.filled_qty <= 0:
                result.outcome = ArbitrageOutcome.NO_FILL
                result.reason = f"buy leg ended {buy_status.raw_status} with zero fill — nothing to neutralize"
                result.completed_at = time.time()
                return result

            # Item 1 (user directive, 2026-08-24, post-incident): if the
            # real BUY fill differs from what was planned, the SELL
            # quantity is recomputed from REAL data — never assumed to
            # equal the pre-trade common_qty. Bounded by: what was
            # actually received (net of any base-asset fee), what the
            # sell exchange ACTUALLY holds right now (a fresh re-read —
            # common_qty's balance check is now stale), and never above
            # the already-revalidated common_qty ceiling.
            actual_sell_exchange_available_qty = await self._get_available_base_balance(sell_exchange, symbol)
            final_sell_qty_raw = min(buy_status.net_base_qty, actual_sell_exchange_available_qty, common_qty)
            sell_step = await self._get_step_size(sell_exchange, symbol)
            sell_qty = round_down_to_step(final_sell_qty_raw, sell_step[0]) if sell_step is not None else 0.0

            # Revalidate net-positive with the REAL buy cost and a FRESH
            # sell-side snapshot (never the pre-buy one — the market may
            # have moved) before ever submitting the sell.
            post_buy_expected_profit = None
            still_positive = False
            if sell_step is not None and sell_qty >= sell_step[1] > 0:
                fresh_sell_leg = await self._fetch_leg_snapshot(symbol, sell_exchange, "sell")
                if fresh_sell_leg is not None and fresh_sell_leg.tradable:
                    sell_vwap, sell_depth_filled = _vwap_for_target_qty(fresh_sell_leg.depth_levels, sell_qty)
                    sell_notional = sell_qty * fresh_sell_leg.best_bid
                    sell_fee_usd = sell_notional * fresh_sell_leg.taker_fee_rate
                    sell_slippage_pct = (
                        abs(sell_vwap - fresh_sell_leg.best_bid) / fresh_sell_leg.best_bid * 100
                        if fresh_sell_leg.best_bid > 0 and sell_depth_filled > 0 else 0.0
                    )
                    if sell_depth_filled < sell_qty:
                        sell_slippage_pct = max(sell_slippage_pct, 100.0)
                    sell_slippage_cost_usd = sell_notional * (sell_slippage_pct / 100)
                    proportional_buy_cost_usd = (buy_status.avg_fill_price or 0) * sell_qty
                    post_buy_expected_profit = (sell_notional - sell_fee_usd - sell_slippage_cost_usd) - proportional_buy_cost_usd
                    min_notional_ok = fresh_sell_leg.min_notional is None or sell_notional >= fresh_sell_leg.min_notional
                    still_positive = min_notional_ok and post_buy_expected_profit > 0

            if not still_positive:
                neutralize_result = await self._neutralize(buy_exchange, symbol, buy_status.net_base_qty, attempt_id)
                if neutralize_result is None or not neutralize_result.is_filled:
                    live_guard.engage_kill_switch(f"neutralization failed after sell leg not viable post-buy, attempt {attempt_id}")
                    result.outcome = ArbitrageOutcome.NEUTRALIZATION_FAILED
                    result.reason = (
                        f"sell leg not viable after the real buy fill (final_sell_qty={sell_qty}, "
                        f"post_buy_expected_profit={post_buy_expected_profit}) and the {buy_exchange}-side flatten did not confirm filled"
                    )
                else:
                    result.outcome = ArbitrageOutcome.BUY_ONLY_NEUTRALIZED
                    result.reason = (
                        f"sell leg not viable after the real buy fill (final_sell_qty={sell_qty}, "
                        f"post_buy_expected_profit={post_buy_expected_profit}) — flattened on {buy_exchange} instead"
                    )
                    result.neutralization_order_id = neutralize_result.order_id
                    result.neutralization_filled_qty = neutralize_result.filled_qty
                result.completed_at = time.time()
                return result

            sell_client_order_id = f"sell-{attempt_id.hex[:24]}"
            result.sell_client_order_id = sell_client_order_id
            result.sell_submitted_at = time.time()
            try:
                await self._place_market_sell(sell_exchange, symbol, sell_qty, sell_client_order_id)
            except Exception as exc:
                neutralize_result = await self._neutralize(buy_exchange, symbol, buy_status.net_base_qty, attempt_id)
                if neutralize_result is None or not neutralize_result.is_filled:
                    live_guard.engage_kill_switch(f"neutralization failed after sell leg submission error, attempt {attempt_id}: {exc}")
                    result.outcome = ArbitrageOutcome.NEUTRALIZATION_FAILED
                else:
                    result.outcome = ArbitrageOutcome.BUY_ONLY_NEUTRALIZED
                    result.neutralization_order_id = neutralize_result.order_id
                    result.neutralization_filled_qty = neutralize_result.filled_qty
                result.reason = f"sell leg submission raised an ambiguous error: {exc}"
                result.completed_at = time.time()
                return result

            reached, sell_status = await self._await_terminal(
                lambda: self._get_status(sell_exchange, symbol, sell_client_order_id), LEG_CONFIRMATION_TIMEOUT_SECONDS
            )
            if not reached or sell_status is None:
                live_guard.engage_kill_switch(f"sell leg status unknown after timeout for attempt {attempt_id} — DO NOT retry the sell leg blindly")
                result.outcome = ArbitrageOutcome.UNKNOWN_SELL_LEG
                result.reason = "sell leg did not reach a terminal status within the confirmation timeout — manual reconciliation required before any further attempt"
                result.completed_at = time.time()
                return result

            result.sell_exchange_order_id = sell_status.order_id
            result.sell_status = sell_status.raw_status
            result.sell_filled_qty = sell_status.filled_qty
            result.sell_avg_fill_price = sell_status.avg_fill_price
            result.sell_fee_asset = sell_status.fee_asset
            result.sell_fee_amount = sell_status.fee_amount
            result.sell_fee_usd_equivalent = sell_status.fee_usd_equivalent
            result.sell_fees_usd = sell_status.fee_usd_equivalent  # backward-compat alias, now correctly currency-aware
            result.sell_confirmed_at = time.time()

            if sell_status.filled_qty <= 0:
                neutralize_result = await self._neutralize(buy_exchange, symbol, buy_status.net_base_qty, attempt_id)
                if neutralize_result is None or not neutralize_result.is_filled:
                    live_guard.engage_kill_switch(f"neutralization failed after sell leg rejected, attempt {attempt_id}")
                    result.outcome = ArbitrageOutcome.NEUTRALIZATION_FAILED
                    result.reason = "sell leg rejected/expired with zero fill and the buy-exchange-side flatten did not confirm filled"
                else:
                    result.outcome = ArbitrageOutcome.BUY_ONLY_NEUTRALIZED
                    result.reason = "sell leg rejected/expired with zero fill — flattened on the buy exchange"
                    result.neutralization_order_id = neutralize_result.order_id
                    result.neutralization_filled_qty = neutralize_result.filled_qty
                result.completed_at = time.time()
                return result

            # Any residual (buy filled more than sell could match, e.g.
            # the sell exchange only partially filled) is a leftover
            # naked position on the BUY exchange (that's where it was
            # acquired) and must be neutralized there too — never left
            # unhedged just because MOST of the arbitrage worked. Based
            # on net_base_qty (what's actually held), not the gross fill.
            raw_residual_qty = buy_status.net_base_qty - sell_status.filled_qty
            if raw_residual_qty > 0:
                buy_step = await self._get_step_size(buy_exchange, symbol)
                if buy_step is not None:
                    residual_qty = round_down_to_step(raw_residual_qty, buy_step[0])
                    # A residual below the buy exchange's own minimum
                    # simply cannot be sold there and is accepted as
                    # unavoidable dust; only neutralize a residual
                    # actually worth acting on.
                    if residual_qty > 0 and residual_qty >= buy_step[1] and residual_qty * (result.buy_avg_fill_price or 0) > 0.01:
                        await self._neutralize(buy_exchange, symbol, residual_qty, attempt_id)

            # FIX 1 (user directive, 2026-08-24): only ADD the fee to the
            # USDT cost/proceeds when it was actually charged in USDT — a
            # base-asset fee never touched the USDT balance at all (it
            # already shows up as a smaller net_base_qty, which naturally
            # reduces what there was to sell); adding it again here would
            # double-count it (this is exactly how the first real Bybit
            # fill's 2.9179 RVN fee would have inflated the apparent cost
            # by ~$2.92 instead of the real ~$0.01).
            buy_fee_in_usdt = result.buy_fee_usd_equivalent if result.buy_fee_asset == QUOTE_ASSET else 0.0
            sell_fee_in_usdt = result.sell_fee_usd_equivalent if result.sell_fee_asset == QUOTE_ASSET else 0.0
            buy_cost_usd = (result.buy_avg_fill_price or 0) * buy_status.filled_qty + (buy_fee_in_usdt or 0)
            sell_proceeds_usd = (result.sell_avg_fill_price or 0) * sell_status.filled_qty - (sell_fee_in_usdt or 0)
            result.actual_net_pnl_usd = sell_proceeds_usd - buy_cost_usd
            result.prediction_error_usd = (
                result.actual_net_pnl_usd - result.predicted_net_profit_usd if result.predicted_net_profit_usd is not None else None
            )
            result.outcome = ArbitrageOutcome.BOTH_FILLED
            result.completed_at = time.time()
            return result
        finally:
            live_guard.register_arbitrage_end()


live_arbitrage_executor = LiveArbitrageExecutor()
