"""LIVE ARBITRAGE EXECUTOR — Binance <-> Bybit spot, ANY common symbol,
EITHER direction (Phase 3A built this for LUNCUSDT/Binance-buy/Bybit-sell
only; Phase 3, user directive, 2026-08-23, generalizes it: "ne hardcode
pas ... une liste arbitraire" — the symbol/direction are now call-time
parameters, chosen by app.execution.live_ranker from the dynamically
discovered common universe, never fixed in this module).

DANGER: this module can place two real market orders. It is the ONLY
caller of app.execution.binance_live_trade_client and
app.execution.bybit_live_trade_client in the entire codebase
(tests/test_phase3a_isolation.py proves this) and is NEVER imported by
main.py's detection loop or any other automatically-running code — every
invocation of execute_one_arbitrage() is a deliberate, individually
authorized act by an operator, never a loop.

There is no real atomicity between two different exchanges. This module
treats that as the central design constraint, not an edge case:

- Every order submission uses a caller-supplied, unique client order id
  — never generated by retrying with the same id, never reused.
- An ACK (the response from placing an order) is NEVER treated as a fill
  confirmation — every submission is followed by polling
  get_order_status until a genuinely terminal state or a strict timeout.
- A timeout without a terminal status is treated as UNKNOWN, not as
  "probably didn't fill" or "probably did" — the kill switch engages
  immediately and the attempt ends requiring manual reconciliation. This
  module never guesses.
- If the buy leg fills but the sell leg does not, the resulting position
  is NEUTRALIZED by an immediate market sell on the SAME exchange the buy
  happened on — never left as naked directional exposure, and never
  "fixed" by blindly retrying the other leg (which could double the
  position if the first attempt actually succeeded after all under an
  ambiguous response).
- max_concurrent_live_arbitrages (checked via
  app.execution.live_guard.live_guard) prevents two attempts from
  overlapping in the first place — the simplest possible defense against
  compounding leg risk.

Every attempt, whatever its outcome, is meant to be recorded to the
Profit Reality Ledger (app.database.repository.save_live_arbitrage_execution)
by the caller — this module returns a complete LiveArbitrageResult
either way, including for NO_TRADE and UNKNOWN outcomes, so the ledger
never has a "silent gap" for an attempt that was actually made.
"""

import asyncio
import logging
import time
import uuid
from dataclasses import dataclass, field
from enum import StrEnum

from app.execution.binance_account_client import BinanceAccountClient
from app.execution.binance_filters import parse_symbol_rules as parse_binance_symbol_rules
from app.execution.binance_filters import round_down_to_step
from app.execution.binance_live_trade_client import BinanceLiveTradeClient
from app.execution.bybit_client import BybitClient
from app.execution.bybit_live_trade_client import BybitLiveTradeClient
from app.execution.dual_leg_quote import DualLegQuote, LegSnapshot, compute_dual_leg_quote
from app.execution.live_guard import LiveExecutionRefused, live_guard
from app.execution.reality_quote import DEFAULT_TAKER_FEE_RATE

logger = logging.getLogger(__name__)

LEG_CONFIRMATION_TIMEOUT_SECONDS = 15.0
LEG_POLL_INTERVAL_SECONDS = 0.5
EXCHANGES = ("binance", "bybit")


def direction_for(buy_exchange: str, sell_exchange: str) -> str:
    return f"{buy_exchange.upper()}_BUY_{sell_exchange.upper()}_SELL"


class ArbitrageOutcome(StrEnum):
    NO_TRADE_REFUSED = "no_trade_refused"  # live_guard refused before any order was even considered
    NO_TRADE_UNPROFITABLE = "no_trade_unprofitable"  # fresh dual-leg re-check failed the safety-margin gate — no order sent
    NO_FILL = "no_fill"  # buy leg rejected/expired with zero fill — nothing to neutralize
    BOTH_FILLED = "both_filled"
    BUY_ONLY_NEUTRALIZED = "buy_only_neutralized"  # sell leg failed; flattened on the buy exchange
    NEUTRALIZATION_FAILED = "neutralization_failed"  # CRITICAL — manual intervention required, kill switch engaged
    UNKNOWN_BUY_LEG = "unknown_buy_leg"  # timeout/ambiguous response — kill switch engaged
    UNKNOWN_SELL_LEG = "unknown_sell_leg"  # timeout/ambiguous response — kill switch engaged


@dataclass(slots=True)
class LiveArbitrageResult:
    attempt_id: uuid.UUID
    symbol: str
    buy_exchange: str
    sell_exchange: str
    outcome: ArbitrageOutcome
    reason: str | None

    predicted_net_profit_usd: float | None = None
    predicted_fees_usd: float | None = None
    predicted_slippage_pct: float | None = None
    safety_adjusted_predicted_profit_usd: float | None = None

    buy_client_order_id: str | None = None
    buy_exchange_order_id: str | None = None
    buy_status: str | None = None
    buy_filled_qty: float = 0.0
    buy_avg_fill_price: float | None = None
    buy_fees_usd: float | None = None
    buy_submitted_at: float | None = None
    buy_confirmed_at: float | None = None

    sell_client_order_id: str | None = None
    sell_exchange_order_id: str | None = None
    sell_status: str | None = None
    sell_filled_qty: float = 0.0
    sell_avg_fill_price: float | None = None
    sell_fees_usd: float | None = None
    sell_submitted_at: float | None = None
    sell_confirmed_at: float | None = None

    neutralization_order_id: str | None = None
    neutralization_filled_qty: float = 0.0

    actual_net_pnl_usd: float | None = None
    prediction_error_usd: float | None = None

    started_at: float = field(default_factory=time.time)
    completed_at: float | None = None


@dataclass(slots=True)
class _NormalizedOrderStatus:
    order_id: str
    is_terminal: bool
    is_filled: bool
    filled_qty: float
    avg_fill_price: float | None
    fee_usd: float
    raw_status: str


class LiveArbitrageExecutor:
    def __init__(
        self,
        binance_read: BinanceAccountClient | None = None,
        binance_trade: BinanceLiveTradeClient | None = None,
        bybit_read: BybitClient | None = None,
        bybit_trade: BybitLiveTradeClient | None = None,
    ) -> None:
        self._binance_read = binance_read or BinanceAccountClient()
        self._binance_trade = binance_trade or BinanceLiveTradeClient()
        self._bybit_read = bybit_read or BybitClient()
        self._bybit_trade = bybit_trade or BybitLiveTradeClient()

    def _read_client(self, exchange: str):
        return self._binance_read if exchange == "binance" else self._bybit_read

    async def _fresh_dual_leg_quote(
        self, symbol: str, buy_exchange: str, sell_exchange: str, micro_live_cap_usdt: float, master_requested_size_usd: float
    ) -> tuple[DualLegQuote, LegSnapshot, LegSnapshot] | None:
        """Re-runs the EXACT Phase 2F dual-leg reality check with brand
        new live data, for whichever (buy_exchange, sell_exchange) pair
        is being attempted — never trusts a quote computed even seconds
        ago for the actual go/no-go decision."""
        try:
            buy_leg = await self._fetch_leg_snapshot(symbol, buy_exchange, "buy")
            sell_leg = await self._fetch_leg_snapshot(symbol, sell_exchange, "sell")
            if buy_leg is None or sell_leg is None:
                return None
            quote = compute_dual_leg_quote(
                opportunity_id=uuid.uuid4(),
                symbol=symbol,
                buy_leg=buy_leg,
                sell_leg=sell_leg,
                master_requested_size_usd=master_requested_size_usd,
                micro_live_cap_usdt=micro_live_cap_usdt,
            )
            return quote, buy_leg, sell_leg
        except Exception as exc:
            logger.warning("live-arbitrage: fresh dual-leg re-check failed for %s %s->%s: %s", symbol, buy_exchange, sell_exchange, exc)
            return None

    async def _fetch_leg_snapshot(self, symbol: str, exchange: str, side: str) -> LegSnapshot | None:
        now = time.time()
        if exchange == "binance":
            book = await self._binance_read.get_book_ticker(symbol)
            depth = await self._binance_read.get_order_book_depth(symbol, limit=20)
            info = await self._binance_read.get_exchange_info(symbols=[symbol])
            rules = parse_binance_symbol_rules(info, symbol)
            fee = await self._binance_read.get_trade_fee(symbol)
            depth_levels = [(float(p), float(q)) for p, q in depth.get("asks" if side == "buy" else "bids", [])]
            return LegSnapshot(
                exchange="binance",
                side=side,
                best_bid=float(book["bidPrice"]),
                best_ask=float(book["askPrice"]),
                depth_levels=depth_levels,
                min_qty=rules.min_qty,
                step_size=rules.step_size,
                tick_size=rules.tick_size,
                min_notional=rules.min_notional,
                tradable=(rules.status == "TRADING" and rules.is_spot_trading_allowed),
                maker_fee_rate=fee.maker_fee_rate if fee is not None else None,
                taker_fee_rate=fee.taker_fee_rate if fee is not None else DEFAULT_TAKER_FEE_RATE,
                fee_source="real_account_fee" if fee is not None else "estimated_default",
                fetch_started_at=now,
                fetch_completed_at=time.time(),
            )
        else:
            book = await self._bybit_read.get_book_ticker(symbol)
            if book is None:
                return None
            depth = await self._bybit_read.get_order_book_depth(symbol, limit=50)
            rules = await self._bybit_read.get_symbol_rules(symbol)
            if rules is None:
                return None
            fee = await self._bybit_read.get_fee_rate(symbol)
            side_key = "a" if side == "buy" else "b"
            depth_levels = [(float(p), float(q)) for p, q in depth.get("result", {}).get(side_key, [])]
            return LegSnapshot(
                exchange="bybit",
                side=side,
                best_bid=book.bid_price,
                best_ask=book.ask_price,
                depth_levels=depth_levels,
                min_qty=rules.min_order_qty,
                step_size=rules.qty_step,
                tick_size=rules.tick_size,
                min_notional=rules.min_order_amt,
                tradable=rules.is_tradable,
                maker_fee_rate=fee.maker_fee_rate if fee is not None else None,
                taker_fee_rate=fee.taker_fee_rate if fee is not None else DEFAULT_TAKER_FEE_RATE,
                fee_source="real_account_fee" if fee is not None else "estimated_default",
                fetch_started_at=now,
                fetch_completed_at=time.time(),
            )

    async def _await_terminal(self, poll_fn, timeout_seconds: float) -> tuple[bool, object | None]:
        """Polls poll_fn() until it returns a terminal result or the
        timeout elapses. Returns (reached_terminal, last_result) — NEVER
        raises; a poll error just means one more retry until the
        timeout, since polling status is read-only and safe to repeat
        (unlike submitting an order)."""
        deadline = time.time() + timeout_seconds
        last_result = None
        while time.time() < deadline:
            try:
                last_result = await poll_fn()
            except Exception as exc:
                logger.warning("live-arbitrage: status poll failed, retrying: %s", exc)
                last_result = None
            if last_result is not None and getattr(last_result, "is_terminal", False):
                return True, last_result
            await asyncio.sleep(LEG_POLL_INTERVAL_SECONDS)
        return False, last_result

    async def _place_market_buy(self, exchange: str, symbol: str, notional_usdt: float, client_order_id: str) -> None:
        """Bybit fix (2026-08-24): place_market_order now sends
        marketUnit="quoteCoin" for every Buy, meaning qty IS the USDT
        notional itself — passed straight through, never pre-converted
        to an estimated base-asset quantity via a book price (that
        conversion is exactly what made the caller's qty mean something
        different from what the wire payload now says it means)."""
        if exchange == "binance":
            await self._binance_trade.place_market_order(symbol, "BUY", client_order_id=client_order_id, quote_order_qty=notional_usdt)
        else:
            await self._bybit_trade.place_market_order(symbol, "Buy", qty=notional_usdt, order_link_id=client_order_id)

    async def _place_market_sell(self, exchange: str, symbol: str, qty: float, client_order_id: str) -> None:
        if exchange == "binance":
            await self._binance_trade.place_market_order(symbol, "SELL", client_order_id=client_order_id, quantity=qty)
        else:
            await self._bybit_trade.place_market_order(symbol, "Sell", qty=qty, order_link_id=client_order_id)

    async def _get_status(self, exchange: str, symbol: str, client_order_id: str) -> _NormalizedOrderStatus | None:
        if exchange == "binance":
            result = await self._binance_trade.get_order_status(symbol, orig_client_order_id=client_order_id)
            fees_by_asset = result.total_fees_by_asset()
            non_usdt_fees = {a: v for a, v in fees_by_asset.items() if a != "USDT"}
            if non_usdt_fees:
                # Binance can charge the fee in a non-quote asset (BNB
                # discount, or the base asset) — summing those alongside a
                # USDT amount would silently produce a wrong USD total, so
                # they're excluded here and logged instead of pretending
                # the total is precise.
                logger.warning("live-arbitrage: %s order fee(s) charged in non-USDT asset(s), excluded: %s", exchange, non_usdt_fees)
            return _NormalizedOrderStatus(
                order_id=str(result.order_id),
                is_terminal=result.is_terminal,
                is_filled=result.is_filled,
                filled_qty=result.executed_qty,
                avg_fill_price=result.average_fill_price(),
                fee_usd=fees_by_asset.get("USDT", 0.0),
                raw_status=result.status,
            )
        else:
            status = await self._bybit_trade.get_order_status(symbol, order_link_id=client_order_id)
            if status is None:
                return None
            # Assumes Bybit charged the fee in the quote asset (USDT) —
            # Bybit's spot response doesn't break fees out by asset the
            # way Binance's does; a VIP tier or promo that changed this
            # would silently skew actual_net_pnl_usd, which is why
            # prediction_error_usd is also recorded as a tell to investigate.
            return _NormalizedOrderStatus(
                order_id=status.order_id,
                is_terminal=status.is_terminal,
                is_filled=status.is_filled,
                filled_qty=status.cum_exec_qty,
                avg_fill_price=status.avg_price,
                fee_usd=status.cum_exec_fee,
                raw_status=status.order_status,
            )

    async def _get_step_size(self, exchange: str, symbol: str) -> tuple[float, float] | None:
        """Returns (step_size, min_qty) for the given exchange/symbol, or
        None if unavailable — used to round a neutralization/hedge
        quantity to what that exchange will actually accept."""
        if exchange == "binance":
            info = await self._binance_read.get_exchange_info(symbols=[symbol])
            rules = parse_binance_symbol_rules(info, symbol)
            return rules.step_size, rules.min_qty
        rules = await self._bybit_read.get_symbol_rules(symbol)
        if rules is None:
            return None
        return rules.qty_step, rules.min_order_qty

    async def _neutralize(self, exchange: str, symbol: str, qty: float, attempt_id: uuid.UUID) -> _NormalizedOrderStatus | None:
        """Flattens an unwanted position acquired on `exchange` with an
        immediate market SELL on that SAME exchange — never attempts to
        "fix" a one-leg-filled state by retrying the other exchange's
        leg, which could double the position if the original attempt
        actually succeeded after all under an ambiguous response."""
        neutralize_id = f"neutralize-{attempt_id}"
        try:
            await self._place_market_sell(exchange, symbol, qty, neutralize_id)
        except Exception as exc:
            logger.critical("live-arbitrage: NEUTRALIZATION ORDER SUBMISSION FAILED on %s for %s: %s", exchange, attempt_id, exc)
            return None
        reached, result = await self._await_terminal(lambda: self._get_status(exchange, symbol, neutralize_id), LEG_CONFIRMATION_TIMEOUT_SECONDS)
        if not reached:
            logger.critical("live-arbitrage: NEUTRALIZATION ORDER STATUS UNKNOWN on %s for %s", exchange, attempt_id)
            return result
        return result

    async def execute_one_arbitrage(
        self,
        symbol: str,
        buy_exchange: str,
        sell_exchange: str,
        requested_notional_per_leg_usdt: float,
        opportunity_id: uuid.UUID | None = None,
    ) -> LiveArbitrageResult:
        """The entire leg-risk-managed attempt, start to finish, for ANY
        symbol/direction pair the caller (app.execution.live_ranker)
        selects from the dynamically-discovered common universe. Callers
        (never main.py's automatic loop — see this module's own
        docstring) are responsible for persisting the returned result to
        the Profit Reality Ledger."""
        if buy_exchange not in EXCHANGES or sell_exchange not in EXCHANGES or buy_exchange == sell_exchange:
            raise ValueError(f"buy_exchange/sell_exchange must be distinct values from {EXCHANGES}, got {buy_exchange!r}/{sell_exchange!r}")

        attempt_id = uuid.uuid4()
        direction = direction_for(buy_exchange, sell_exchange)
        result = LiveArbitrageResult(
            attempt_id=attempt_id, symbol=symbol, buy_exchange=buy_exchange, sell_exchange=sell_exchange,
            outcome=ArbitrageOutcome.NO_TRADE_REFUSED, reason=None,
        )

        try:
            live_guard.assert_arbitrage_allowed(symbol, direction, requested_notional_per_leg_usdt)
        except LiveExecutionRefused as exc:
            result.reason = str(exc)
            result.completed_at = time.time()
            return result

        live_guard.register_arbitrage_start()
        try:
            fresh = await self._fresh_dual_leg_quote(symbol, buy_exchange, sell_exchange, requested_notional_per_leg_usdt, requested_notional_per_leg_usdt)
            if fresh is None:
                result.outcome = ArbitrageOutcome.NO_TRADE_UNPROFITABLE
                result.reason = "fresh dual-leg re-check unavailable (data fetch failed)"
                result.completed_at = time.time()
                return result
            quote, _buy_leg, _sell_leg = fresh

            result.predicted_net_profit_usd = quote.net_profit_usd
            result.predicted_fees_usd = quote.buy_fee_usd + quote.sell_fee_usd
            result.predicted_slippage_pct = max(quote.buy_slippage_pct, quote.sell_slippage_pct)

            # Same data-driven safety-margin methodology as Phase 2E/2F —
            # no fixed number invented here; a caller with a
            # recommend_safety_margin_usd() figure from
            # app.reporting.dual_leg_edge should pass it forward via
            # requested_notional_per_leg_usdt sizing upstream. In the
            # absence of a supplied margin this defaults to 0 (bare
            # net_profit_usd > 0), which is intentionally the WEAKER
            # bound — callers building the first-live gate must apply
            # the stricter, measured margin themselves before calling.
            safety_margin_usd = 0.0
            result.safety_adjusted_predicted_profit_usd = quote.net_profit_usd - safety_margin_usd

            if not quote.executable or result.safety_adjusted_predicted_profit_usd <= 0:
                result.outcome = ArbitrageOutcome.NO_TRADE_UNPROFITABLE
                result.reason = quote.reason or "net profit after safety margin is not strictly positive"
                result.completed_at = time.time()
                return result

            buy_client_order_id = f"live-{attempt_id}-buy"
            result.buy_client_order_id = buy_client_order_id
            result.buy_submitted_at = time.time()
            try:
                await self._place_market_buy(buy_exchange, symbol, requested_notional_per_leg_usdt, buy_client_order_id)
            except Exception as exc:
                live_guard.engage_kill_switch(f"buy leg submission raised an ambiguous error: {exc}")
                result.outcome = ArbitrageOutcome.UNKNOWN_BUY_LEG
                result.reason = str(exc)
                result.completed_at = time.time()
                return result

            reached, buy_status = await self._await_terminal(
                lambda: self._get_status(buy_exchange, symbol, buy_client_order_id), LEG_CONFIRMATION_TIMEOUT_SECONDS
            )
            if not reached or buy_status is None:
                live_guard.engage_kill_switch(f"buy leg status unknown after timeout for attempt {attempt_id}")
                result.outcome = ArbitrageOutcome.UNKNOWN_BUY_LEG
                result.reason = "buy leg did not reach a terminal status within the confirmation timeout"
                result.completed_at = time.time()
                return result

            result.buy_exchange_order_id = buy_status.order_id
            result.buy_status = buy_status.raw_status
            result.buy_filled_qty = buy_status.filled_qty
            result.buy_avg_fill_price = buy_status.avg_fill_price
            result.buy_fees_usd = buy_status.fee_usd
            result.buy_confirmed_at = time.time()

            if buy_status.filled_qty <= 0:
                result.outcome = ArbitrageOutcome.NO_FILL
                result.reason = f"buy leg ended {buy_status.raw_status} with zero fill — nothing to neutralize"
                result.completed_at = time.time()
                return result

            sell_step = await self._get_step_size(sell_exchange, symbol)
            sell_qty = round_down_to_step(buy_status.filled_qty, sell_step[0]) if sell_step is not None else 0.0
            if sell_step is None or sell_qty < sell_step[1] or sell_qty <= 0:
                neutralize_result = await self._neutralize(buy_exchange, symbol, buy_status.filled_qty, attempt_id)
                if neutralize_result is None or not neutralize_result.is_filled:
                    live_guard.engage_kill_switch(f"neutralization failed after buy fill too small to hedge on {sell_exchange}, attempt {attempt_id}")
                    result.outcome = ArbitrageOutcome.NEUTRALIZATION_FAILED
                    result.reason = f"buy leg filled below {sell_exchange}'s tradable minimum and the {buy_exchange}-side flatten did not confirm filled"
                else:
                    result.outcome = ArbitrageOutcome.BUY_ONLY_NEUTRALIZED
                    result.reason = f"buy fill was below {sell_exchange}'s minimum tradable size — flattened on {buy_exchange} instead"
                    result.neutralization_order_id = neutralize_result.order_id
                    result.neutralization_filled_qty = neutralize_result.filled_qty
                result.completed_at = time.time()
                return result

            sell_client_order_id = f"live-{attempt_id}-sell"
            result.sell_client_order_id = sell_client_order_id
            result.sell_submitted_at = time.time()
            try:
                await self._place_market_sell(sell_exchange, symbol, sell_qty, sell_client_order_id)
            except Exception as exc:
                neutralize_result = await self._neutralize(buy_exchange, symbol, buy_status.filled_qty, attempt_id)
                if neutralize_result is None or not neutralize_result.is_filled:
                    live_guard.engage_kill_switch(f"neutralization failed after sell leg submission error, attempt {attempt_id}: {exc}")
                    result.outcome = ArbitrageOutcome.NEUTRALIZATION_FAILED
                else:
                    result.outcome = ArbitrageOutcome.BUY_ONLY_NEUTRALIZED
                    result.neutralization_order_id = neutralize_result.order_id
                    result.neutralization_filled_qty = neutralize_result.filled_qty
                result.reason = f"sell leg submission raised an ambiguous error: {exc}"
                result.completed_at = time.time()
                return result

            reached, sell_status = await self._await_terminal(
                lambda: self._get_status(sell_exchange, symbol, sell_client_order_id), LEG_CONFIRMATION_TIMEOUT_SECONDS
            )
            if not reached or sell_status is None:
                live_guard.engage_kill_switch(f"sell leg status unknown after timeout for attempt {attempt_id} — DO NOT retry the sell leg blindly")
                result.outcome = ArbitrageOutcome.UNKNOWN_SELL_LEG
                result.reason = "sell leg did not reach a terminal status within the confirmation timeout — manual reconciliation required before any further attempt"
                result.completed_at = time.time()
                return result

            result.sell_exchange_order_id = sell_status.order_id
            result.sell_status = sell_status.raw_status
            result.sell_filled_qty = sell_status.filled_qty
            result.sell_avg_fill_price = sell_status.avg_fill_price
            result.sell_fees_usd = sell_status.fee_usd
            result.sell_confirmed_at = time.time()

            if sell_status.filled_qty <= 0:
                neutralize_result = await self._neutralize(buy_exchange, symbol, buy_status.filled_qty, attempt_id)
                if neutralize_result is None or not neutralize_result.is_filled:
                    live_guard.engage_kill_switch(f"neutralization failed after sell leg rejected, attempt {attempt_id}")
                    result.outcome = ArbitrageOutcome.NEUTRALIZATION_FAILED
                    result.reason = "sell leg rejected/expired with zero fill and the buy-exchange-side flatten did not confirm filled"
                else:
                    result.outcome = ArbitrageOutcome.BUY_ONLY_NEUTRALIZED
                    result.reason = "sell leg rejected/expired with zero fill — flattened on the buy exchange"
                    result.neutralization_order_id = neutralize_result.order_id
                    result.neutralization_filled_qty = neutralize_result.filled_qty
                result.completed_at = time.time()
                return result

            # Any residual (buy filled more than sell could match, e.g.
            # the sell exchange only partially filled) is a leftover
            # naked position on the BUY exchange (that's where it was
            # acquired) and must be neutralized there too — never left
            # unhedged just because MOST of the arbitrage worked.
            raw_residual_qty = buy_status.filled_qty - sell_status.filled_qty
            if raw_residual_qty > 0:
                buy_step = await self._get_step_size(buy_exchange, symbol)
                if buy_step is not None:
                    residual_qty = round_down_to_step(raw_residual_qty, buy_step[0])
                    # A residual below the buy exchange's own minimum
                    # simply cannot be sold there and is accepted as
                    # unavoidable dust; only neutralize a residual
                    # actually worth acting on.
                    if residual_qty > 0 and residual_qty >= buy_step[1] and residual_qty * (result.buy_avg_fill_price or 0) > 0.01:
                        await self._neutralize(buy_exchange, symbol, residual_qty, attempt_id)

            buy_cost_usd = (result.buy_avg_fill_price or 0) * buy_status.filled_qty + (result.buy_fees_usd or 0)
            sell_proceeds_usd = (result.sell_avg_fill_price or 0) * sell_status.filled_qty - (result.sell_fees_usd or 0)
            result.actual_net_pnl_usd = sell_proceeds_usd - buy_cost_usd
            result.prediction_error_usd = (
                result.actual_net_pnl_usd - result.predicted_net_profit_usd if result.predicted_net_profit_usd is not None else None
            )
            result.outcome = ArbitrageOutcome.BOTH_FILLED
            result.completed_at = time.time()
            return result
        finally:
            live_guard.register_arbitrage_end()


live_arbitrage_executor = LiveArbitrageExecutor()
